"""
Tier list completa del parche actual con todos los campeones.
Formato plano: (dd_name, display_name, role, tier, win_rate, pick_rate, ban_rate)
"""
from __future__ import annotations

CURRENT_PATCH = "16.10"

TIER_COLORS = {
    "S+": "#ff4444",
    "S":  "#ff8800",
    "A":  "#ffcc00",
    "B":  "#88cc00",
    "C":  "#aaaaaa",
}

# Columnas: (dd_name, display_name, role, tier, wr, pr, br)
# Roles: TOP, JUNGLE, MIDDLE, BOTTOM, UTILITY
CHAMPION_TIERS = [
    # ── TOP ────────────────────────────────────────────────────────────────────
    ("Darius",       "Darius",       "TOP", "S+", 52.3, 8.1,  12.5),
    ("Garen",        "Garen",        "TOP", "S+", 53.1, 7.2,   8.3),
    ("Camille",      "Camille",      "TOP", "S+", 51.8, 9.5,  15.2),
    ("Ambessa",      "Ambessa",      "TOP", "S+", 52.0, 7.8,  19.0),
    ("Aatrox",       "Aatrox",       "TOP", "S",  51.2, 11.3, 18.7),
    ("Fiora",        "Fiora",        "TOP", "S",  50.9, 6.8,   9.1),
    ("Gwen",         "Gwen",         "TOP", "S",  51.5, 6.2,  10.3),
    ("Illaoi",       "Illaoi",       "TOP", "S",  51.8, 5.9,   8.7),
    ("Irelia",       "Irelia",       "TOP", "S",  50.2, 7.9,  13.5),
    ("Malphite",     "Malphite",     "TOP", "S",  51.5, 5.9,   7.2),
    ("Renekton",     "Renekton",     "TOP", "S",  50.7, 8.4,  11.3),
    ("ChoGath",      "Cho'Gath",     "TOP", "A",  50.8, 4.2,   3.9),
    ("Gangplank",    "Gangplank",    "TOP", "A",  50.1, 5.3,   6.2),
    ("Jax",          "Jax",          "TOP", "A",  49.5, 9.1,  10.2),
    ("KSante",       "K'Sante",      "TOP", "A",  50.3, 6.7,  12.1),
    ("Mordekaiser",  "Mordekaiser",  "TOP", "A",  50.4, 6.2,   8.9),
    ("Nasus",        "Nasus",        "TOP", "A",  50.2, 5.1,   4.2),
    ("Olaf",         "Olaf",         "TOP", "A",  51.1, 4.8,   5.3),
    ("Ornn",         "Ornn",         "TOP", "A",  50.6, 4.1,   5.0),
    ("Rumble",       "Rumble",       "TOP", "A",  50.9, 3.8,   4.1),
    ("Sion",         "Sion",         "TOP", "A",  50.2, 4.5,   5.8),
    ("Teemo",        "Teemo",        "TOP", "A",  49.3, 4.8,   6.1),
    ("Urgot",        "Urgot",        "TOP", "A",  51.0, 4.3,   5.5),
    ("Vladimir",     "Vladimir",     "TOP", "A",  50.5, 5.7,   7.1),
    ("MonkeyKing",   "Wukong",       "TOP", "A",  51.2, 5.2,   5.9),
    ("DrMundo",      "Dr. Mundo",    "TOP", "B",  51.3, 4.0,   3.5),
    ("Gnar",         "Gnar",         "TOP", "B",  49.5, 4.7,   5.2),
    ("Gragas",       "Gragas",       "TOP", "B",  49.2, 3.1,   3.8),
    ("Jayce",        "Jayce",        "TOP", "B",  49.8, 5.4,   7.3),
    ("Kayle",        "Kayle",        "TOP", "B",  49.7, 4.2,   5.0),
    ("Kennen",       "Kennen",       "TOP", "B",  49.9, 3.5,   4.1),
    ("Kled",         "Kled",         "TOP", "B",  49.5, 2.9,   3.2),
    ("Pantheon",     "Pantheon",     "TOP", "B",  49.3, 5.1,   7.8),
    ("Poppy",        "Poppy",        "TOP", "B",  50.1, 3.3,   3.0),
    ("Quinn",        "Quinn",        "TOP", "B",  50.4, 2.8,   2.5),
    ("Riven",        "Riven",        "TOP", "B",  49.2, 5.8,   8.1),
    ("Sett",         "Sett",         "TOP", "B",  50.7, 6.1,   9.3),
    ("Shen",         "Shen",         "TOP", "B",  50.3, 3.9,   4.5),
    ("Singed",       "Singed",       "TOP", "B",  51.5, 2.1,   2.0),
    ("TahmKench",    "Tahm Kench",   "TOP", "B",  50.1, 3.2,   3.7),
    ("Tryndamere",   "Tryndamere",   "TOP", "B",  49.8, 4.5,   5.6),
    ("Trundle",      "Trundle",      "TOP", "B",  51.0, 2.7,   2.4),
    ("Volibear",     "Volibear",     "TOP", "B",  50.2, 5.3,   6.8),
    ("Yasuo",        "Yasuo",        "TOP", "B",  49.1, 7.5,  11.2),
    ("Yone",         "Yone",         "TOP", "B",  49.5, 6.2,   9.5),
    ("Yorick",       "Yorick",       "TOP", "B",  51.7, 3.4,   3.8),
    ("Akali",        "Akali",        "TOP", "C",  48.9, 4.1,   8.2),
    ("Aurora",       "Aurora",       "TOP", "C",  48.5, 3.2,   5.1),
    ("Cassiopeia",   "Cassiopeia",   "TOP", "C",  48.8, 1.9,   2.5),
    ("Heimerdinger", "Heimerdinger", "TOP", "C",  47.8, 1.5,   2.1),
    ("Lissandra",    "Lissandra",    "TOP", "C",  48.4, 1.8,   2.3),
    ("Ryze",         "Ryze",         "TOP", "C",  48.1, 2.3,   3.1),
    ("Swain",        "Swain",        "TOP", "C",  48.7, 2.1,   2.8),
    ("Zac",          "Zac",          "TOP", "C",  48.3, 2.0,   2.2),

    # ── JUNGLE ─────────────────────────────────────────────────────────────────
    ("Briar",        "Briar",        "JUNGLE", "S+", 52.5,  9.1, 16.3),
    ("Kayn",         "Kayn",         "JUNGLE", "S+", 51.9,  8.7, 12.3),
    ("LeeSin",       "Lee Sin",      "JUNGLE", "S+", 50.8, 14.5, 20.1),
    ("Viego",        "Viego",        "JUNGLE", "S+", 52.8,  9.3, 14.1),
    ("Evelynn",      "Evelynn",      "JUNGLE", "S",  51.5,  6.2,  9.8),
    ("Graves",       "Graves",       "JUNGLE", "S",  51.1,  8.3, 11.7),
    ("Hecarim",      "Hecarim",      "JUNGLE", "S",  51.5,  7.5, 10.3),
    ("JarvanIV",     "Jarvan IV",    "JUNGLE", "S",  51.3,  7.1,  9.8),
    ("Nidalee",      "Nidalee",      "JUNGLE", "S",  51.8,  5.9,  8.5),
    ("Vi",           "Vi",           "JUNGLE", "S",  51.7,  6.8,  8.2),
    ("Amumu",        "Amumu",        "JUNGLE", "A",  52.3,  7.8,  9.5),
    ("BelVeth",      "Bel'Veth",     "JUNGLE", "A",  51.0,  5.5,  8.3),
    ("Diana",        "Diana",        "JUNGLE", "A",  50.1,  5.8,  7.1),
    ("Ekko",         "Ekko",         "JUNGLE", "A",  49.8,  6.7,  8.9),
    ("KhaZix",       "Kha'Zix",      "JUNGLE", "A",  50.5,  7.2, 10.4),
    ("Kindred",      "Kindred",      "JUNGLE", "A",  50.3,  5.1,  7.0),
    ("Nocturne",     "Nocturne",     "JUNGLE", "A",  51.2,  5.8,  8.1),
    ("RekSai",       "Rek'Sai",      "JUNGLE", "A",  51.5,  4.3,  5.2),
    ("Sejuani",      "Sejuani",      "JUNGLE", "A",  51.0,  4.9,  5.8),
    ("Volibear",     "Volibear",     "JUNGLE", "A",  51.3,  5.5,  7.2),
    ("Warwick",      "Warwick",      "JUNGLE", "A",  52.1,  5.9,  6.1),
    ("XinZhao",      "Xin Zhao",     "JUNGLE", "A",  51.8,  6.2,  7.8),
    ("Rammus",       "Rammus",       "JUNGLE", "A",  53.1,  4.1,  5.2),
    ("Elise",        "Elise",        "JUNGLE", "B",  50.5,  4.8,  6.2),
    ("Fiddlesticks", "Fiddlesticks", "JUNGLE", "B",  51.8,  4.2,  6.5),
    ("Gragas",       "Gragas",       "JUNGLE", "B",  49.2,  3.5,  3.9),
    ("Ivern",        "Ivern",        "JUNGLE", "B",  51.5,  2.1,  2.3),
    ("Lillia",       "Lillia",       "JUNGLE", "B",  50.2,  4.9,  5.8),
    ("Maokai",       "Maokai",       "JUNGLE", "B",  51.0,  3.1,  3.5),
    ("MasterYi",     "Master Yi",    "JUNGLE", "B",  51.5,  7.2,  9.8),
    ("NunuWillump",  "Nunu",         "JUNGLE", "B",  51.3,  4.5,  4.8),
    ("Rengar",       "Rengar",       "JUNGLE", "B",  49.5,  5.3,  7.1),
    ("Shaco",        "Shaco",        "JUNGLE", "B",  50.8,  4.1,  5.9),
    ("Shyvana",      "Shyvana",      "JUNGLE", "B",  50.9,  3.5,  4.2),
    ("Taliyah",      "Taliyah",      "JUNGLE", "B",  50.5,  4.8,  6.3),
    ("Trundle",      "Trundle",      "JUNGLE", "B",  51.3,  3.2,  3.0),
    ("Udyr",         "Udyr",         "JUNGLE", "B",  51.0,  3.8,  4.1),
    ("MonkeyKing",   "Wukong",       "JUNGLE", "B",  50.7,  4.3,  5.0),
    ("Zac",          "Zac",          "JUNGLE", "B",  51.2,  4.5,  5.3),
    ("Poppy",        "Poppy",        "JUNGLE", "C",  49.5,  1.8,  2.0),
    ("Skarner",      "Skarner",      "JUNGLE", "C",  49.0,  3.2,  4.1),
    ("Teemo",        "Teemo",        "JUNGLE", "C",  47.2,  1.1,  1.5),
    ("Twitch",       "Twitch",       "JUNGLE", "C",  48.5,  1.9,  2.3),
    ("Pantheon",     "Pantheon",     "JUNGLE", "C",  48.8,  2.1,  3.0),
    ("Karthus",      "Karthus",      "JUNGLE", "C",  50.1,  3.5,  5.2),

    # ── MIDDLE ─────────────────────────────────────────────────────────────────
    ("Ahri",         "Ahri",         "MIDDLE", "S+", 51.9, 10.2, 16.3),
    ("Cassiopeia",   "Cassiopeia",   "MIDDLE", "S+", 52.5,  5.1,  8.9),
    ("Syndra",       "Syndra",       "MIDDLE", "S+", 52.1,  7.8, 13.5),
    ("Veigar",       "Veigar",       "MIDDLE", "S+", 52.7,  6.9, 10.2),
    ("AurelionSol",  "Aurelion Sol", "MIDDLE", "S",  52.0,  4.8,  9.1),
    ("Leblanc",      "LeBlanc",      "MIDDLE", "S",  50.9,  7.5, 12.8),
    ("Lissandra",    "Lissandra",    "MIDDLE", "S",  51.5,  4.2,  6.8),
    ("Malzahar",     "Malzahar",     "MIDDLE", "S",  52.0,  5.3,  8.5),
    ("Orianna",      "Orianna",      "MIDDLE", "S",  51.4,  6.3,  9.7),
    ("Taliyah",      "Taliyah",      "MIDDLE", "S",  51.3,  4.1,  5.9),
    ("Viktor",       "Viktor",       "MIDDLE", "S",  51.8,  8.1, 14.2),
    ("Zed",          "Zed",          "MIDDLE", "S",  50.2,  9.8, 17.3),
    ("Akali",        "Akali",        "MIDDLE", "A",  49.8, 10.1, 18.7),
    ("Corki",        "Corki",        "MIDDLE", "A",  50.9,  3.5,  4.1),
    ("Diana",        "Diana",        "MIDDLE", "A",  50.3,  4.9,  6.2),
    ("Ekko",         "Ekko",         "MIDDLE", "A",  49.9,  5.8,  7.5),
    ("Fizz",         "Fizz",         "MIDDLE", "A",  50.5,  5.2,  8.9),
    ("Galio",        "Galio",        "MIDDLE", "A",  51.1,  5.5,  7.3),
    ("Hwei",         "Hwei",         "MIDDLE", "A",  51.3,  6.1,  8.4),
    ("Irelia",       "Irelia",       "MIDDLE", "A",  49.5,  5.8,  9.8),
    ("Karma",        "Karma",        "MIDDLE", "A",  51.0,  4.3,  5.1),
    ("Katarina",     "Katarina",     "MIDDLE", "A",  50.3,  7.8, 12.5),
    ("Mel",          "Mel",          "MIDDLE", "A",  51.5,  5.2,  9.3),
    ("Naafiri",      "Naafiri",      "MIDDLE", "A",  51.8,  4.5,  7.2),
    ("Sylas",        "Sylas",        "MIDDLE", "A",  50.7,  8.9, 13.1),
    ("TwistedFate",  "Twisted Fate", "MIDDLE", "A",  50.1,  5.8,  7.9),
    ("Yasuo",        "Yasuo",        "MIDDLE", "A",  49.3, 13.2, 19.5),
    ("Yone",         "Yone",         "MIDDLE", "A",  49.8,  9.5, 15.3),
    ("Zoe",          "Zoe",          "MIDDLE", "A",  51.2,  5.1,  8.8),
    ("Annie",        "Annie",        "MIDDLE", "B",  51.2,  3.8,  5.1),
    ("Azir",         "Azir",         "MIDDLE", "B",  47.2,  3.5,  6.1),
    ("Brand",        "Brand",        "MIDDLE", "B",  50.8,  4.3,  6.5),
    ("Heimerdinger", "Heimerdinger", "MIDDLE", "B",  50.3,  2.1,  3.5),
    ("Jayce",        "Jayce",        "MIDDLE", "B",  49.5,  4.1,  5.8),
    ("Kassadin",     "Kassadin",     "MIDDLE", "B",  50.5,  3.9,  5.7),
    ("Neeko",        "Neeko",        "MIDDLE", "B",  50.9,  3.2,  4.1),
    ("Pantheon",     "Pantheon",     "MIDDLE", "B",  49.3,  4.5,  6.8),
    ("Qiyana",       "Qiyana",       "MIDDLE", "B",  50.1,  3.8,  5.3),
    ("Ryze",         "Ryze",         "MIDDLE", "B",  48.7,  4.1,  6.2),
    ("Seraphine",    "Seraphine",    "MIDDLE", "B",  50.5,  3.5,  4.8),
    ("Swain",        "Swain",        "MIDDLE", "B",  50.8,  3.2,  4.5),
    ("Talon",        "Talon",        "MIDDLE", "B",  50.3,  5.9,  8.2),
    ("VelKoz",       "Vel'Koz",      "MIDDLE", "B",  51.2,  2.8,  3.5),
    ("Vex",          "Vex",          "MIDDLE", "B",  51.5,  4.1,  5.9),
    ("Xerath",       "Xerath",       "MIDDLE", "B",  51.0,  3.5,  4.8),
    ("Zilean",       "Zilean",       "MIDDLE", "B",  52.0,  2.1,  2.8),
    ("Aurora",       "Aurora",       "MIDDLE", "C",  48.5,  3.1,  5.0),
    ("Gangplank",    "Gangplank",    "MIDDLE", "C",  49.2,  2.8,  3.5),
    ("Gragas",       "Gragas",       "MIDDLE", "C",  48.8,  1.9,  2.1),
    ("Kennen",       "Kennen",       "MIDDLE", "C",  49.1,  2.3,  2.8),
    ("Orianna",      "Orianna",      "MIDDLE", "S",  51.4,  6.3,  9.7),
    ("Rumble",       "Rumble",       "MIDDLE", "C",  48.9,  2.5,  2.9),
    ("Vladimir",     "Vladimir",     "MIDDLE", "C",  49.3,  3.1,  3.8),

    # ── BOTTOM (ADC) ───────────────────────────────────────────────────────────
    ("Caitlyn",      "Caitlyn",      "BOTTOM", "S+", 51.2, 10.8, 12.7),
    ("Jhin",         "Jhin",         "BOTTOM", "S+", 51.8, 13.7, 14.3),
    ("Jinx",         "Jinx",         "BOTTOM", "S+", 52.5, 11.3, 15.2),
    ("MissFortune",  "Miss Fortune", "BOTTOM", "S+", 52.3,  8.9,  9.1),
    ("Ashe",         "Ashe",         "BOTTOM", "S",  51.9,  9.5, 10.8),
    ("Kaisa",        "Kai'Sa",       "BOTTOM", "S",  50.8, 15.1, 18.9),
    ("Nilah",        "Nilah",        "BOTTOM", "S",  51.7,  5.2,  6.8),
    ("Smolder",      "Smolder",      "BOTTOM", "S",  51.3,  6.8,  9.2),
    ("Tristana",     "Tristana",     "BOTTOM", "S",  51.1,  7.2,  8.3),
    ("Draven",       "Draven",       "BOTTOM", "A",  49.3,  5.9,  8.2),
    ("Ezreal",       "Ezreal",       "BOTTOM", "A",  49.5, 16.3, 12.1),
    ("KogMaw",       "Kog'Maw",      "BOTTOM", "A",  52.1,  4.8,  5.5),
    ("Lucian",       "Lucian",       "BOTTOM", "A",  50.1,  9.7, 13.5),
    ("Sivir",        "Sivir",        "BOTTOM", "A",  51.7,  5.8,  6.9),
    ("Twitch",       "Twitch",       "BOTTOM", "A",  50.2,  4.1,  5.7),
    ("Vayne",        "Vayne",        "BOTTOM", "A",  49.8,  8.2, 10.3),
    ("Xayah",        "Xayah",        "BOTTOM", "A",  50.5,  7.1,  9.8),
    ("Zeri",         "Zeri",         "BOTTOM", "A",  50.9,  5.5,  7.3),
    ("Aphelios",     "Aphelios",     "BOTTOM", "B",  49.9,  8.5, 11.2),
    ("Corki",        "Corki",        "BOTTOM", "B",  50.2,  3.1,  3.5),
    ("Kalista",      "Kalista",      "BOTTOM", "B",  48.3,  3.2,  5.9),
    ("Samira",       "Samira",       "BOTTOM", "B",  49.7,  7.8, 12.4),
    ("Varus",        "Varus",        "BOTTOM", "B",  50.3,  5.9,  6.1),
    ("Veigar",       "Veigar",       "BOTTOM", "B",  51.5,  3.2,  4.5),
    ("Ziggs",        "Ziggs",        "BOTTOM", "B",  50.8,  4.1,  4.9),
    ("Brand",        "Brand",        "BOTTOM", "C",  49.5,  1.8,  2.5),
    ("Heimerdinger", "Heimerdinger", "BOTTOM", "C",  48.9,  1.2,  1.8),
    ("Seraphine",    "Seraphine",    "BOTTOM", "C",  49.8,  2.5,  3.1),
    ("Senna",        "Senna",        "BOTTOM", "C",  49.2,  3.1,  3.9),
    ("Yasuo",        "Yasuo",        "BOTTOM", "C",  48.5,  2.8,  3.2),

    # ── UTILITY (SUPPORT) ──────────────────────────────────────────────────────
    ("Lulu",         "Lulu",         "UTILITY", "S+", 52.8,  9.3, 11.5),
    ("Nautilus",     "Nautilus",     "UTILITY", "S+", 52.1, 11.8, 16.2),
    ("RenataGlasc",  "Renata Glasc", "UTILITY", "S+", 52.3,  6.1,  9.8),
    ("Thresh",       "Thresh",       "UTILITY", "S+", 51.3, 12.5, 18.7),
    ("Blitzcrank",   "Blitzcrank",   "UTILITY", "S",  51.7, 10.2, 15.8),
    ("Janna",        "Janna",        "UTILITY", "S",  53.2,  7.1,  8.9),
    ("Leona",        "Leona",        "UTILITY", "S",  50.8,  9.5, 14.7),
    ("Milio",        "Milio",        "UTILITY", "S",  52.5,  5.8,  7.3),
    ("Morgana",      "Morgana",      "UTILITY", "S",  51.5,  9.7, 13.4),
    ("Soraka",       "Soraka",       "UTILITY", "S",  52.9,  6.8,  7.2),
    ("Alistar",      "Alistar",      "UTILITY", "A",  50.7,  5.4,  7.8),
    ("Bard",         "Bard",         "UTILITY", "A",  51.2,  5.1,  6.3),
    ("Brand",        "Brand",        "UTILITY", "A",  51.8,  6.2,  9.5),
    ("Karma",        "Karma",        "UTILITY", "A",  51.1,  7.8,  9.3),
    ("Nami",         "Nami",         "UTILITY", "A",  51.9,  6.3,  8.1),
    ("Neeko",        "Neeko",        "UTILITY", "A",  51.5,  3.8,  5.2),
    ("Pyke",         "Pyke",         "UTILITY", "A",  49.8,  7.9, 12.3),
    ("Rell",         "Rell",         "UTILITY", "A",  51.4,  4.9,  6.1),
    ("Senna",        "Senna",        "UTILITY", "A",  50.5,  8.1, 10.8),
    ("VelKoz",       "Vel'Koz",      "UTILITY", "A",  51.8,  3.5,  5.1),
    ("Xerath",       "Xerath",       "UTILITY", "A",  51.5,  4.2,  6.0),
    ("Zilean",       "Zilean",       "UTILITY", "A",  53.4,  4.2,  5.1),
    ("Zyra",         "Zyra",         "UTILITY", "A",  51.3,  4.8,  6.2),
    ("Braum",        "Braum",        "UTILITY", "B",  50.8,  5.1,  6.5),
    ("Galio",        "Galio",        "UTILITY", "B",  50.3,  3.2,  4.1),
    ("Lux",          "Lux",          "UTILITY", "B",  50.9,  7.5,  9.2),
    ("Maokai",       "Maokai",       "UTILITY", "B",  52.1,  3.1,  3.5),
    ("Pantheon",     "Pantheon",     "UTILITY", "B",  49.2,  3.8,  5.5),
    ("Rakan",        "Rakan",        "UTILITY", "B",  50.1,  5.8,  7.9),
    ("Seraphine",    "Seraphine",    "UTILITY", "B",  51.2,  4.5,  5.8),
    ("Sona",         "Sona",         "UTILITY", "B",  52.5,  4.1,  4.3),
    ("Swain",        "Swain",        "UTILITY", "B",  50.5,  3.5,  4.7),
    ("Taric",        "Taric",        "UTILITY", "B",  52.3,  2.8,  2.5),
    ("Yuumi",        "Yuumi",        "UTILITY", "B",  51.0,  5.9,  7.1),
    ("Zac",          "Zac",          "UTILITY", "C",  49.5,  1.5,  1.8),
    ("Heimerdinger", "Heimerdinger", "UTILITY", "C",  48.5,  1.1,  1.5),
    ("Tahm Kench",   "Tahm Kench",   "UTILITY", "C",  50.2,  2.1,  2.5),
]

# ── Función de consulta ───────────────────────────────────────────────────────

def get_tier_list_by_role(role: str) -> dict[str, list[dict]]:
    """Devuelve {tier: [champ_dicts]} para el rol dado, sin duplicados."""
    seen = set()
    result: dict[str, list] = {"S+": [], "S": [], "A": [], "B": [], "C": []}
    for dd, name, r, tier, wr, pr, br in CHAMPION_TIERS:
        if r != role:
            continue
        key = (dd, r)
        if key in seen:
            continue
        seen.add(key)
        result.setdefault(tier, []).append(
            {"name": name, "dd": dd, "wr": wr, "pr": pr, "br": br}
        )
    return result
